# Generated by Django 2.1.7 on 2019-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Arrivedatdestinationstation', 'Arrived at destination station'), ('ArrivedatHub', 'Arrived at Hub'), ('Shipmentpickedup', 'Shipment picked up'), ('Waiting', 'Waiting')], default='Waiting', max_length=30),
        ),
    ]
