# Generated by Django 2.1.7 on 2019-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_customer',
            name='result',
            field=models.CharField(choices=[('check', 'check'), ('uncheck', 'uncheck')], default='uncheck', max_length=7),
        ),
    ]
