# Generated by Django 2.1.7 on 2019-05-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190429_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='blacklist',
            field=models.BooleanField(default=False),
        ),
    ]
