# Generated by Django 2.1.7 on 2019-05-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190501_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='admin',
            field=models.ManyToManyField(blank=True, null=True, through='products.Admin_Customer', to='products.Admin'),
        ),
    ]
