# Generated by Django 2.1.7 on 2019-05-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190502_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.TextField(null=True),
        ),
    ]
