# Generated by Django 2.1.7 on 2019-05-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190503_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
